title: Website minimal theme
logo: /assets/img/logo.png
description: >
  Minimal is a theme for GitHub Pages.
  This is a brief description of who I am.

# Dark theme configuration
theme: 
  name: jekyll-theme-slate

# Sidebar content
sidebar:
  - title: About Me
    image: /assets/img/your_image.jpg
    image_alt: Francisco Javier Ornelas
    text: >
      I am a PhD Student at UCLA.
  - title: Links
    links:
      - title: GitHub
        url: https://github.com/fjornelas
      # - title: LinkedIn
      #   url: https://linkedin.com/in/yourusername
      # Add more links as needed

# Optional configurations
show_downloads: true
google_analytics:

# Any other configurations you need

